### ISSUE TITLE
Roadmap and things to do

### ISSUE THREAD

**Issue by jakobrosenberg** [roxiness/routify#191]
This is a list of things that would be nice to have. Feel free to add suggestions.

- [ ] Meta capture option for grabbing an excerpt of the current file. https://github.com/sveltech/routify/issues/190
- [x] Bundler-free template https://github.com/sveltech/routify/issues/176
- [x] Document common pitfalls (ie. local temp dir when using Electron)
- [x] Get started on Roxi
- [x] Search feature
- [x] Fix fallback image for serviceworkers (works offline, but not for 404s)
- [ ] AfterPageLoad should be called after a component with no default slot (instead of when layout array is empty) [link](https://discordapp.com/channels/683709869626490889/683709871362801740/718041903790030901)

**2.0 specific**
- [x] Add option to let `isAncestor` treat a sibling index as parent. (Used in BaseTransition)
- [x] Hash based routing
- [x] Replace `basepath` with `urlTransform` for better control
- [x] Add `_folder.svelte` and `_module.svelte` as alias for `_layout.svelte`. This should make it easier to reason about the file's function and purpose. `_layout.svelte` will likely be deprecated.
- [x] Enable dynamic imports by default
- [x] Trim/remove redundant packages
- [x] More helpful errors
- [x] Change path resolution to be match traditional filesystems
- [x] Merge `_folder.svelte` (_layout.svelte) into the dir nodes.
- [x] Release beta (semantic-release disagrees)

**wishlist**
- [ ] `.routify-ignore`
- [ ] I18N URLs https://github.com/sveltech/routify/issues/183
- [x] Hash based routing https://github.com/sveltech/routify/issues/22
- [ ] Server routes https://github.com/sveltech/routify/issues/84

**Comment by justinharkey** [comment]
I mentioned this in the Discord but for the Scheme/structure documentation I think it would be helpful to have a full tree example, similar to what is shown on https://sapper.svelte.dev/docs/#Sapper_app_structure

The example project gives great insight into the workings of Routify, I think it would be helpful to integrate the example into the documentation. For example on the Scheme/structure page you could list out the pages from the example project with explanations. That way the project and documentation both have the same examples/teaching.

**Comment by Wolfr** [comment]
We have this here, but it's limited: https://routify.dev/guide/starter-Template

**Comment by jakobrosenberg** [comment]
I have added the frontpage hero tree to the structure section.

**Comment by Tommertom** [comment]
Not sure if this issue is to track lots of feature requests, but if so I'd like to add file based ignore to the list.

The value of the router is the fact that is file based, not needing to make tons of declarations (e.g. Angular router). Along that line of "Developer Experience" I would expect it to be possible to add a `.routify-ignore` file (or something silimar) to the folder, instead of having to declare ignores as per https://routify.dev/docs/config/build specs touching files I don't want to be touching every time - or even worse, adding a `.filter` in the component setting the Router component.

Maybe a repeat of earlier cases, but a point raised from my end.

Keep up the good work. Going to migrate to 2.0 now, to make my Sunday morning really good :)

**Comment by jakobrosenberg** [comment]
@Tommertom how do you feel about `routify.config.js`?

**Comment by Tommertom** [comment]
> @Tommertom how do you feel about `routify.config.js`?

Thx for the prompt reply. I feel the same as before. Needing to open and editor to do what I did in a different way, namely file based. Again, the core advantage of a file based router to me is not having to edit files to manage routes, everything I think I need one.

**Comment by jakobrosenberg** [comment]
I get your point. What confuses me is how `.routify-ignore` solves the configuration files issue. Won't you just end up with even more configuration files if config attributes are abstracted to individual files? This is the primary reason I added the `routify` option to `package.json`. To provide an option which reduces clutter and amount of configuration files in the root.

Another concern is SSOT. Using `.routify-ignore` forces you to have multiple configs for the same library, the moment you need to configure anything else. Troubleshooting a misconfigured app, can take you on a major detour, if you forget/are unaware of an extra config.

Lastly, more options require more documentation and more maintenance.

Some of the current options
```javascript
// routify.config.js
module.exports = {
  extensions: 'svelte,html,svx,md',
  ignore: [
    'file-a.svelte',
    'file-b.svelte',
    'file-c.svelte',
  ]
}
```

```javascript
// package.json
"routify": {
  "extensions": "svelte,html,svx,md",
  "ignore": [
    "file-a.svelte",
    "file-b.svelte",
    "file-c.svelte",
  ]
}
```

Not saying `.routify-ignore` shouldn't or couldn't be added. Just want to make sure the pros, cons and pitfalls are covered.

**Comment by Tommertom** [comment]
> Not saying `.routify-ignore` shouldn't or couldn't be added. Just want to make sure the pros, cons and pitfalls are covered.

Thx for this. I think it will be good to get a bit of evidence based input from others here as well, as honestly I am not yet a big consumer of routify features. Will these issues occur as you say so and do they outweigh the pros of being able to organise routes using the file system (e,g. using the `touch` command to simply exlcude something)? The latter also referring to the (personal) preference of developers on how they organise their files.

I understand your point of having a config file in a folder to exclude specific components from the routing stack looks similar to the existing config features. That indeed may defeat the purpose. Only if you organise features in folder structures, this may work better?

On the other hand, why not offer both ways, as means of flexibility. Either way, a consideration for the roadmap. Needs more empirical support if you ask me, and not sure if it should stay in this issue. 

And yes, the documentation on exclusion is a bit minimalistic. Maybe you can add the examples given here already to it?

**Comment by jakobrosenberg** [comment]
Added `.routify-ignore` to the wishlist for now. You're right that this should probably have it's own issue.
